# Generated by Django 4.2.7 on 2023-12-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseAI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AImodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AIfile', models.FileField(upload_to='')),
            ],
        ),
    ]
