# Generated by Django 4.2.7 on 2024-01-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseAI', '0002_aimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
            ],
        ),
    ]
